// DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../boards/mazduino-compact/connectors/can.yaml
// auto-generated by PinoutLogic.java based on ../../../boards/mazduino-compact/connectors/main.yaml
#include "pch.h"

// see comments at declaration in pin_repository.h
const char* getBoardSpecificPinName(brain_pin_e brainPin) {
	switch (brainPin) {
		case Gpio::A0:
			return "MAP (PA0)";
		case Gpio::A1:
			return "AFR (PA1)";
		case Gpio::A15:
			return "Fan (PA15)";
		case Gpio::A4:
			return "CLT (PA4)";
		case Gpio::A5:
			return "IAT (PA5)";
		case Gpio::A6:
			return "TPS (PA6)";
		case Gpio::A7:
			return "Spare Analog 2 (PA7)";
		case Gpio::B0:
			return "AC Switch (PB0)";
		case Gpio::B1:
			return "Spare Analog 1 (PB1)";
		case Gpio::B13:
			return "INJ 4 (PB13)";
		case Gpio::B14:
			return "INJ 3 (PB14)";
		case Gpio::B15:
			return "INJ 2 (PB15)";
		case Gpio::C7:
			return "AC Relay (PC7)";
		case Gpio::C8:
			return "Fuel Pump (PC8)";
		case Gpio::C9:
			return "Tach (PC9)";
		case Gpio::CAN_INPUT_0:
			return "CAN Switch 1";
		case Gpio::CAN_INPUT_1:
			return "CAN Switch 2";
		case Gpio::CAN_INPUT_2:
			return "CAN Switch 3";
		case Gpio::CAN_INPUT_3:
			return "CAN Switch 4";
		case Gpio::CAN_INPUT_4:
			return "CAN Switch 5";
		case Gpio::CAN_INPUT_5:
			return "CAN Switch 6";
		case Gpio::CAN_INPUT_6:
			return "CAN Switch 7";
		case Gpio::CAN_INPUT_7:
			return "CAN Switch 8";
		case Gpio::D10:
			return "2nd Solenoid (PD10)";
		case Gpio::D13:
			return "IGN 3 (PD13)";
		case Gpio::D14:
			return "HS Out 2 (PD14)";
		case Gpio::D15:
			return "HS Out 1 (PD15)";
		case Gpio::D3:
			return "CKP (PD3)";
		case Gpio::D4:
			return "CMP (PD4)";
		case Gpio::D7:
			return "VSS (PD7)";
		case Gpio::D8:
			return "INJ 1 (PD8)";
		case Gpio::D9:
			return "Idle Solenoid (PD9)";
		case Gpio::E13:
			return "Clutch (PE13)";
		case Gpio::E14:
			return "IGN 2 (PE14)";
		case Gpio::E15:
			return "IGN 1 (PE15)";
		case Gpio::E5:
			return "IGN 4 (PE5)";
		case Gpio::E8:
			return "Main Relay (PE8)";
		default:
			return nullptr;
	}
	return nullptr;
}
