// DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../boards/mazduino-mini6ch/connectors/can.yaml
// auto-generated by PinoutLogic.java based on ../../../boards/mazduino-mini6ch/connectors/main.yaml
#pragma once

