// DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../boards/mazduino-mini6ch/connectors/can.yaml
// auto-generated by PinoutLogic.java based on ../../../boards/mazduino-mini6ch/connectors/main.yaml
#pragma once

Gpio GENERATED_OUTPUTS[] = {
	Gpio::D8, // INJ 1 (PD8)
	Gpio::B15, // INJ 2 (PB15)
	Gpio::B14, // INJ 3 (PB14)
	Gpio::B13, // INJ 4 (PB13)
	Gpio::D9, // INJ 5 (PD9)
	Gpio::E8, // INJ 6 (PE8)
	Gpio::E15, // IGN 1 (PE15)
	Gpio::E14, // IGN 2 (PE14)
	Gpio::D13, // IGN 3 (PD13)
	Gpio::E5, // IGN 4 (PE5)
	Gpio::E2, // IGN 5 (PE2)
	Gpio::E3, // IGN 6 (PE3)
	Gpio::C8, // Fuel Pump (PC8)
	Gpio::C5, // Main Relay (PC5)
	Gpio::D10, // Idle Solenoid (PD10)
	Gpio::E9, // 2nd Solenoid (PE9)
	Gpio::A15, // Fan (PA15)
	Gpio::C9, // Tach (PC9)
	Gpio::C7, // AC Relay (PC7)
	Gpio::A8, // ETB PWM (PA8)
	Gpio::B8, // ETB DIR (PB8)
	Gpio::B9, // ETB DIS (PB9)
	Gpio::D12, // Stepper DIR (PD12)
	Gpio::D15, // Stepper STEP (PD15)
	Gpio::D14, // Stepper EN (PD14)
// "INJ 1 (PD8)",
// "INJ 2 (PB15)",
// "INJ 3 (PB14)",
// "INJ 4 (PB13)",
// "INJ 5 (PD9)",
// "INJ 6 (PE8)",
// "IGN 1 (PE15)",
// "IGN 2 (PE14)",
// "IGN 3 (PD13)",
// "IGN 4 (PE5)",
// "IGN 5 (PE2)",
// "IGN 6 (PE3)",
// "Fuel Pump (PC8)",
// "Main Relay (PC5)",
// "Idle Solenoid (PD10)",
// "2nd Solenoid (PE9)",
// "Fan (PA15)",
// "Tach (PC9)",
// "AC Relay (PC7)",
// "ETB PWM (PA8)",
// "ETB DIR (PB8)",
// "ETB DIS (PB9)",
// "Stepper DIR (PD12)",
// "Stepper STEP (PD15)",
// "Stepper EN (PD14)",
}
