// DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../boards/mazduino-mega100-512/connectors/can.yaml
#include "pch.h"

// see comments at declaration in pin_repository.h
const char* getBoardSpecificPinName(brain_pin_e brainPin) {
	switch (brainPin) {
		case Gpio::CAN_INPUT_0:
			return "CAN Switch 1";
		case Gpio::CAN_INPUT_1:
			return "CAN Switch 2";
		case Gpio::CAN_INPUT_2:
			return "CAN Switch 3";
		case Gpio::CAN_INPUT_3:
			return "CAN Switch 4";
		case Gpio::CAN_INPUT_4:
			return "CAN Switch 5";
		case Gpio::CAN_INPUT_5:
			return "CAN Switch 6";
		case Gpio::CAN_INPUT_6:
			return "CAN Switch 7";
		case Gpio::CAN_INPUT_7:
			return "CAN Switch 8";
		default:
			return nullptr;
	}
	return nullptr;
}
