// DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../boards/mazduino-core/connectors/can.yaml
// auto-generated by PinoutLogic.java based on ../../../boards/mazduino-core/connectors/main.yaml
#include "pch.h"

// see comments at declaration in pin_repository.h
const char* getBoardSpecificPinName(brain_pin_e brainPin) {
	switch (brainPin) {
		case Gpio::A0:
			return "Analog Volt 5 (PA0)";
		case Gpio::A1:
			return "Analog Volt 6 (PA1)";
		case Gpio::A2:
			return "Analog Volt 7 - PPS2 (PA2)";
		case Gpio::A3:
			return "Analog Volt 8 (PA3)";
		case Gpio::A4:
			return "Analog Volt 9 - PPS (PA4)";
		case Gpio::A5:
			return "Analog Volt 10 - AFR (PA5)";
		case Gpio::A6:
			return "Analog Volt 11 (PA6)";
		case Gpio::A8:
			return "HS 2 (PA8)";
		case Gpio::A9:
			return "HS 1 (PA9)";
		case Gpio::B0:
			return "Analog Temp 3 - CLT (PB0)";
		case Gpio::B1:
			return "Analog Temp 4 (PB1)";
		case Gpio::B4:
			return "LS 8 (PB4)";
		case Gpio::B5:
			return "LS 9 (PB5)";
		case Gpio::B6:
			return "LS 10 - Fuel Pump (PB6)";
		case Gpio::B7:
			return "LS 11 - Fan (PB7)";
		case Gpio::B8:
			return "LS 12 - Main Relay (PB8)";
		case Gpio::B9:
			return "LS 13 (PB9)";
		case Gpio::C0:
			return "Analog Volt 1 - MAP (PC0)";
		case Gpio::C1:
			return "Analog Volt 2 - TPS (PC1)";
		case Gpio::C2:
			return "Analog Volt 3 - TPS2 (PC2)";
		case Gpio::C3:
			return "Analog Volt 4 (PC3)";
		case Gpio::C4:
			return "Analog Temp 1 (PC4)";
		case Gpio::C5:
			return "Analog Temp 2 - IAT (PC5)";
		case Gpio::C6:
			return "Digital 1 - CKP (PC6)";
		case Gpio::C7:
			return "IGN 5 (PC7)";
		case Gpio::C8:
			return "IGN 4 (PC8)";
		case Gpio::C9:
			return "IGN 3 (PC9)";
		case Gpio::CAN_INPUT_0:
			return "CAN Switch 1";
		case Gpio::CAN_INPUT_1:
			return "CAN Switch 2";
		case Gpio::CAN_INPUT_2:
			return "CAN Switch 3";
		case Gpio::CAN_INPUT_3:
			return "CAN Switch 4";
		case Gpio::CAN_INPUT_4:
			return "CAN Switch 5";
		case Gpio::CAN_INPUT_5:
			return "CAN Switch 6";
		case Gpio::CAN_INPUT_6:
			return "CAN Switch 7";
		case Gpio::CAN_INPUT_7:
			return "CAN Switch 8";
		case Gpio::D10:
			return "ETB1 DIR (PD10)";
		case Gpio::D11:
			return "ETB1 DIS (PD11)";
		case Gpio::D12:
			return "ETB1 PWM (PD12)";
		case Gpio::D13:
			return "ETB2 PWM (PD13)";
		case Gpio::D14:
			return "HS 4 (PD14)";
		case Gpio::D15:
			return "HS 3 (PD15)";
		case Gpio::D3:
			return "IGN 2 (PD3)";
		case Gpio::D4:
			return "IGN 1 (PD4)";
		case Gpio::D7:
			return "LS 1 (PD7)";
		case Gpio::D8:
			return "ETB2 DIS (PD8)";
		case Gpio::D9:
			return "ETB2 DIR (PD9)";
		case Gpio::E0:
			return "LS 14 (PE0)";
		case Gpio::E1:
			return "LS 15 (PE1)";
		case Gpio::E11:
			return "Digital 2 (PE11)";
		case Gpio::E12:
			return "Digital 3 (PE12)";
		case Gpio::E13:
			return "Digital 5 (PE13)";
		case Gpio::E14:
			return "Digital 4 (PE14)";
		case Gpio::E15:
			return "Digital 6 (PE15)";
		case Gpio::E2:
			return "LS 16 (PE2)";
		case Gpio::E7:
			return "VR 1 (PE7)";
		case Gpio::E8:
			return "VR 2 (PE8)";
		case Gpio::G10:
			return "LS 3 (PG10)";
		case Gpio::G11:
			return "LS 4 (PG11)";
		case Gpio::G12:
			return "LS 5 (PG12)";
		case Gpio::G13:
			return "LS 6 (PG13)";
		case Gpio::G14:
			return "LS 7 (PG14)";
		case Gpio::G2:
			return "IGN 12 (PG2)";
		case Gpio::G3:
			return "IGN 11 (PG3)";
		case Gpio::G4:
			return "IGN 10 (PG4)";
		case Gpio::G5:
			return "IGN 9 (PG5)";
		case Gpio::G6:
			return "IGN 8 (PG6)";
		case Gpio::G7:
			return "IGN 7 (PG7)";
		case Gpio::G8:
			return "IGN 6 (PG8)";
		case Gpio::G9:
			return "LS 2 (PG9)";
		default:
			return nullptr;
	}
	return nullptr;
}
