// DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../boards/mazduino-core/connectors/can.yaml
// auto-generated by PinoutLogic.java based on ../../../boards/mazduino-core/connectors/main.yaml
#pragma once

Gpio GENERATED_OUTPUTS[] = {
	Gpio::D7, // LS 1 (PD7)
	Gpio::G9, // LS 2 (PG9)
	Gpio::G10, // LS 3 (PG10)
	Gpio::G11, // LS 4 (PG11)
	Gpio::G12, // LS 5 (PG12)
	Gpio::G13, // LS 6 (PG13)
	Gpio::G14, // LS 7 (PG14)
	Gpio::B4, // LS 8 (PB4)
	Gpio::B5, // LS 9 (PB5)
	Gpio::B6, // LS 10 - Fuel Pump (PB6)
	Gpio::B7, // LS 11 - Fan (PB7)
	Gpio::B8, // LS 12 - Main Relay (PB8)
	Gpio::B9, // LS 13 (PB9)
	Gpio::E0, // LS 14 (PE0)
	Gpio::E1, // LS 15 (PE1)
	Gpio::E2, // LS 16 (PE2)
	Gpio::A9, // HS 1 (PA9)
	Gpio::A8, // HS 2 (PA8)
	Gpio::D15, // HS 3 (PD15)
	Gpio::D14, // HS 4 (PD14)
	Gpio::D4, // IGN 1 (PD4)
	Gpio::D3, // IGN 2 (PD3)
	Gpio::C9, // IGN 3 (PC9)
	Gpio::C8, // IGN 4 (PC8)
	Gpio::C7, // IGN 5 (PC7)
	Gpio::G8, // IGN 6 (PG8)
	Gpio::G7, // IGN 7 (PG7)
	Gpio::G6, // IGN 8 (PG6)
	Gpio::G5, // IGN 9 (PG5)
	Gpio::G4, // IGN 10 (PG4)
	Gpio::G3, // IGN 11 (PG3)
	Gpio::G2, // IGN 12 (PG2)
	Gpio::D12, // ETB1 PWM (PD12)
	Gpio::D10, // ETB1 DIR (PD10)
	Gpio::D11, // ETB1 DIS (PD11)
	Gpio::D13, // ETB2 PWM (PD13)
	Gpio::D9, // ETB2 DIR (PD9)
	Gpio::D8, // ETB2 DIS (PD8)
// "LS 1 (PD7)",
// "LS 2 (PG9)",
// "LS 3 (PG10)",
// "LS 4 (PG11)",
// "LS 5 (PG12)",
// "LS 6 (PG13)",
// "LS 7 (PG14)",
// "LS 8 (PB4)",
// "LS 9 (PB5)",
// "LS 10 - Fuel Pump (PB6)",
// "LS 11 - Fan (PB7)",
// "LS 12 - Main Relay (PB8)",
// "LS 13 (PB9)",
// "LS 14 (PE0)",
// "LS 15 (PE1)",
// "LS 16 (PE2)",
// "HS 1 (PA9)",
// "HS 2 (PA8)",
// "HS 3 (PD15)",
// "HS 4 (PD14)",
// "IGN 1 (PD4)",
// "IGN 2 (PD3)",
// "IGN 3 (PC9)",
// "IGN 4 (PC8)",
// "IGN 5 (PC7)",
// "IGN 6 (PG8)",
// "IGN 7 (PG7)",
// "IGN 8 (PG6)",
// "IGN 9 (PG5)",
// "IGN 10 (PG4)",
// "IGN 11 (PG3)",
// "IGN 12 (PG2)",
// "ETB1 PWM (PD12)",
// "ETB1 DIR (PD10)",
// "ETB1 DIS (PD11)",
// "ETB2 PWM (PD13)",
// "ETB2 DIR (PD9)",
// "ETB2 DIS (PD8)",
}
