// DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../boards/mazduino-lite/connectors/can.yaml
// auto-generated by PinoutLogic.java based on ../../../boards/mazduino-lite/connectors/main.yaml
#pragma once

Gpio GENERATED_OUTPUTS[] = {
	Gpio::D8, // INJ 1 (PD8)
	Gpio::B15, // INJ 2 (PB15)
	Gpio::B14, // INJ 3 (PB14)
	Gpio::B13, // INJ 4 (PB13)
	Gpio::E15, // IGN 1 (PE15)
	Gpio::E14, // IGN 2 (PE14)
	Gpio::C8, // Fuel Pump (PC8)
	Gpio::E8, // Main Relay (PE8)
	Gpio::D9, // Idle Solenoid (PD9)
	Gpio::D10, // 2nd Solenoid (PD10)
	Gpio::A15, // Fan (PA15)
	Gpio::C9, // Tach (PC9)
	Gpio::C7, // AC Relay (PC7)
// "INJ 1 (PD8)",
// "INJ 2 (PB15)",
// "INJ 3 (PB14)",
// "INJ 4 (PB13)",
// "IGN 1 (PE15)",
// "IGN 2 (PE14)",
// "Fuel Pump (PC8)",
// "Main Relay (PE8)",
// "Idle Solenoid (PD9)",
// "2nd Solenoid (PD10)",
// "Fan (PA15)",
// "Tach (PC9)",
// "AC Relay (PC7)",
}
